package com.github.ajalt.clikt.completion

import com.github.ajalt.clikt.completion.CompletionCandidates.Custom.ShellType
import com.github.ajalt.clikt.core.BaseCliktCommand
import com.github.ajalt.clikt.parameters.options.Option

/**
 * Generates PowerShell completion scripts using [Register-ArgumentCompleter](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter)
 * with the `-Native` switch for Clikt commands.
 *
 * The generated script:
 * - Uses `$commandAst.CommandElements` (the PowerShell AST) to detect the current
 *   command context by collecting bare-word arguments, mirroring how
 *   [about_Functions_Argument_Completion](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_argument_completion)
 *   recommends native completers work.
 * - Emits plain strings (compatible with `-Native` switch, which auto-converts
 *   each string to a `[CompletionResult]` object).
 * - Registers a single completer using `switch -Wildcard` on the joined
 *   command-path to dispatch based on current subcommand context.
 */
internal object PowershellCompletionGenerator {
    fun generatePowershellCompletion(command: BaseCliktCommand<*>): String {
        if (!command.hasPowershellCompletionRequirements) return ""
        val rootName = command.currentContext.commandNameWithParents().first()
        val nodes = collectNodes(command)
        return buildString {
            appendLine("# Command completion for $rootName")
            appendLine("# Generated by Clikt")
            appendLine()
            appendLine("Register-ArgumentCompleter -Native -CommandName '$rootName' -ScriptBlock {")
            appendLine("    param(\$wordToComplete, \$commandAst, \$cursorPosition)")
            appendLine()
            appendLine("    \$commandPath = @()")
            appendLine("    for (\$i = 1; \$i -lt \$commandAst.CommandElements.Count; \$i++) {")
            appendLine("        \$e = \$commandAst.CommandElements[\$i]")
            appendLine("        if (\$e -is [StringConstantExpressionAst] -and \$e.StringConstantType -eq [StringConstantType]::BareWord -and -not \$e.Value.StartsWith('-')) {")
            appendLine("            \$commandPath += \$e.Value")
            appendLine("        }")
            appendLine("    }")
            appendLine()
            appendLine("    \$cmdKey = \$commandPath -join ' '")
            appendLine()
            emitOptionNameSection(nodes)
            appendLine()
            emitFallbackSection(nodes)
            append("}")
        }
    }

    private data class CmdNode(
        val command: BaseCliktCommand<*>,
        val cmdKey: String,
    )

    private fun collectNodes(command: BaseCliktCommand<*>): List<CmdNode> {
        val result = mutableListOf<CmdNode>()
        fun recurse(cmd: BaseCliktCommand<*>, prefix: String) {
            result.add(CmdNode(cmd, prefix))
            for (sub in cmd._subcommands) {
                recurse(sub, if (prefix.isEmpty()) sub.commandName else "$prefix ${sub.commandName}")
            }
        }
        recurse(command, "")
        result.sortByDescending { it.cmdKey.length }
        val rootIdx = result.indexOfFirst { it.cmdKey.isEmpty() }
        if (rootIdx >= 0) {
            result.add(result.removeAt(rootIdx))
        }
        return result
    }

    private fun StringBuilder.emitOptionNameSection(nodes: List<CmdNode>) {
        val relevant = nodes.filter { node ->
            node.command._options.filterNot { it.hidden }
                .flatMap { it.allNames }.any { it.startsWith('-') }
        }
        if (relevant.isEmpty()) return

        appendLine("    if (\$wordToComplete -match '^-') {")
        appendLine("        \$opts = switch -Wildcard (\$cmdKey) {")
        for (node in relevant) {
            val opts = node.command._options.filterNot { it.hidden }
            val names = opts.flatMap { it.allNames }.filter { it.startsWith('-') }
            if (names.isEmpty()) continue
            val pattern = if (node.cmdKey.isEmpty()) "''" else "'${node.cmdKey}'"
            appendLine("            $pattern {")
            names.joinTo(this, "; ") { "'${it.escSingleQuote}'" }
            appendLine("")
            appendLine("            }")
        }
        appendLine("            default { }")
        appendLine("        }")
        appendLine("        return \$opts | Where-Object { \$_ -like \"\$wordToComplete*\" }")
        appendLine("    }")
    }

    private fun StringBuilder.emitFallbackSection(nodes: List<CmdNode>) {
        appendLine("    switch -Wildcard (\$cmdKey) {")
        for (node in nodes) {
            emitFallbackCase(node, "        ")
            if (node.cmdKey.isNotEmpty()) {
                emitFallbackCaseWildcard(node, "        ")
            }
        }
        val root = nodes.find { it.cmdKey.isEmpty() }
        if (root != null) {
            appendLine("        '*' {")
            emitOptionValueCompletions(root.command, "            ")
            emitFallbackCompletions(root.command, "            ")
            appendLine("        }")
        }
        appendLine("    }")
    }

    private fun StringBuilder.emitFallbackCase(node: CmdNode, indent: String) {
        val cmd = node.command
        val optionsWithValues = cmd._options.filterNot { it.hidden }.filter { it.nvalues.first > 0 }
        val hasOptions = optionsWithValues.isNotEmpty()
        val subcommands = cmd._subcommands

        val hasFallback = subcommands.isNotEmpty() || cmd._arguments.isNotEmpty()
        if (!hasOptions && !hasFallback) return

        val pattern = if (node.cmdKey.isEmpty()) "''" else "'${node.cmdKey}'"
        appendLine("${indent}$pattern {")
        if (hasOptions) {
            emitOptionValueCompletions(cmd, "$indent    ")
        }
        if (hasFallback) {
            if (hasOptions) appendLine()
            emitFallbackCompletions(cmd, "$indent    ")
        }
        appendLine("${indent}}")
    }

    private fun StringBuilder.emitFallbackCaseWildcard(node: CmdNode, indent: String) {
        val cmd = node.command
        val optionsWithValues = cmd._options.filterNot { it.hidden }.filter { it.nvalues.first > 0 }
        val hasOptions = optionsWithValues.isNotEmpty()
        val subcommands = cmd._subcommands

        val hasFallback = subcommands.isNotEmpty() || cmd._arguments.isNotEmpty()
        if (!hasOptions && !hasFallback) return

        appendLine("${indent}'${node.cmdKey} *' {")
        if (hasOptions) {
            emitOptionValueCompletions(cmd, "$indent    ")
        }
        if (hasFallback) {
            if (hasOptions) appendLine()
            emitFallbackCompletions(cmd, "$indent    ")
        }
        appendLine("${indent}}")
    }

    private fun StringBuilder.emitOptionValueCompletions(command: BaseCliktCommand<*>, indent: String) {
        val optionsWithValues = command._options.filterNot { it.hidden }.filter { it.nvalues.first > 0 }
        if (optionsWithValues.isEmpty()) return

        appendLine("${indent}\$lastElement = \$commandAst.CommandElements[\$commandAst.CommandElements.Count - 1]")
        appendLine("${indent}\$lastText = \$lastElement.Value")
        appendLine()
        appendLine("${indent}if (\$lastText.StartsWith('-')) {")
        appendLine("${indent}    switch -Regex (\$lastText) {")
        for (option in optionsWithValues) {
            val names = option.allNames.filter { it.startsWith('-') }
            if (names.isEmpty()) continue
            val pattern = names.joinToString("|") { it.escRegex }
            appendLine("${indent}        '^($pattern)$' {")
            appendParamCompletion(option.completionCandidates, "$indent            ")
            appendLine("${indent}            return")
            appendLine("${indent}        }")
        }
        appendLine("${indent}    }")
        appendLine("${indent}} elseif (\$commandAst.CommandElements.Count -gt 2) {")
        appendLine("${indent}    \$prevElement = \$commandAst.CommandElements[\$commandAst.CommandElements.Count - 2]")
        appendLine("${indent}    \$prevText = \$prevElement.Value")
        appendLine("${indent}    if (\$prevText.StartsWith('-')) {")
        appendLine("${indent}        switch -Regex (\$prevText) {")
        for (option in optionsWithValues) {
            val names = option.allNames.filter { it.startsWith('-') }
            if (names.isEmpty()) continue
            val pattern = names.joinToString("|") { it.escRegex }
            appendLine("${indent}            '^($pattern)$' {")
            appendParamCompletion(option.completionCandidates, "$indent                ")
            appendLine("${indent}                return")
            appendLine("${indent}            }")
        }
        appendLine("${indent}        }")
        appendLine("${indent}    }")
        appendLine("${indent}}")
    }

    private fun StringBuilder.emitFallbackCompletions(command: BaseCliktCommand<*>, indent: String) {
        val subcommands = command._subcommands
        val arguments = command._arguments
        val hasSubs = subcommands.isNotEmpty()
        val hasArgs = arguments.isNotEmpty()
        if (!hasSubs && !hasArgs) return

        appendLine("${indent}return @(")
        if (hasSubs) {
            for (sub in subcommands) {
                appendLine("${indent}    '${sub.commandName}'")
            }
        }
        for (arg in arguments) {
            val cc = arg.completionCandidates
            when (cc) {
                is CompletionCandidates.None -> {}
                is CompletionCandidates.Path -> {
                    appendLine("${indent}    Get-ChildItem \"\$wordToComplete*\" -ErrorAction SilentlyContinue | ForEach-Object { \$_.FullName }")
                }
                is CompletionCandidates.Hostname -> {}
                is CompletionCandidates.Username -> {
                    appendLine("${indent}    Get-LocalUser -ErrorAction SilentlyContinue | Where-Object { \$_.Name -like \"\$wordToComplete*\" } | ForEach-Object { \$_.Name }")
                }
                is CompletionCandidates.Fixed -> {
                    for (candidate in cc.candidates) {
                        appendLine("${indent}    '${candidate.escSingleQuote}'")
                    }
                }
                is CompletionCandidates.Custom -> {
                    val custom = cc.generator(ShellType.POWERSHELL)
                    if (custom != null) {
                        appendLine("${indent}    $custom")
                    }
                }
            }
        }
        appendLine("${indent}) | Where-Object { \$_ -like \"\$wordToComplete*\" }")
    }

    private fun StringBuilder.appendParamCompletion(cc: CompletionCandidates, indent: String) {
        when (cc) {
            is CompletionCandidates.None -> {}
            is CompletionCandidates.Path -> {
                appendLine("${indent}Get-ChildItem \"\$wordToComplete*\" -ErrorAction SilentlyContinue | ForEach-Object { \$_.FullName }")
            }
            is CompletionCandidates.Hostname -> {}
            is CompletionCandidates.Username -> {
                appendLine("${indent}Get-LocalUser -ErrorAction SilentlyContinue | Where-Object { \$_.Name -like \"\$wordToComplete*\" } | ForEach-Object { \$_.Name }")
            }
            is CompletionCandidates.Fixed -> {
                appendLine("${indent}return @(")
                for (candidate in cc.candidates) {
                    appendLine("${indent}    '${candidate.escSingleQuote}'")
                }
                appendLine("${indent}) | Where-Object { \$_ -like \"\$wordToComplete*\" }")
            }
            is CompletionCandidates.Custom -> {
                val custom = cc.generator(ShellType.POWERSHELL)
                if (custom != null) {
                    appendLine("${indent}$custom")
                }
            }
        }
    }

    private val BaseCliktCommand<*>.hasPowershellCompletionRequirements: Boolean
        get() = _arguments.isNotEmpty()
                || _subcommands.isNotEmpty()
                || _options.flatMap { it.allNames }.any { it.startsWith('-') }

    private val Option.allNames get() = names + secondaryNames

    private val String.escSingleQuote: String
        get() = replace("'", "''")

    private val String.escRegex: String
        get() = replace(Regex("[.\\\\+*?\\[\\^\\]\$(){}|]")) { "\\${it.value}" }
}
