package com.github.ajalt.clikt.completion

import com.github.ajalt.clikt.completion.CompletionCandidates.Custom.ShellType
import com.github.ajalt.clikt.core.BaseCliktCommand
import com.github.ajalt.clikt.parameters.options.Option

/**
 * Generates PowerShell completion scripts using [Register-ArgumentCompleter](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter)
 * with the `-Native` switch for Clikt commands.
 *
 * The generated script:
 * - Uses `$commandAst.CommandElements` (the PowerShell AST) to detect the current
 *   command context by counting bare-word arguments, mirroring how
 *   [about_Functions_Argument_Completion](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_argument_completion)
 *   recommends native completers work.
 * - Emits [CompletionResult](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.completionresult)
 *   objects via `[CompletionResult]::new()` with appropriate
 *   [CompletionResultType](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.completionresulttype)
 *   (`ParameterName` for option names, `ParameterValue` for values and subcommands).
 * - Registers one completer per command level, each gated by a context-depth check.
 */
internal object PowershellCompletionGenerator {
    fun generatePowershellCompletion(command: BaseCliktCommand<*>): String {
        if (!command.hasPowershellCompletionRequirements) return ""
        val rootName = command.currentContext.commandNameWithParents().first()
        return buildString {
            appendLine("# Command completion for $rootName")
            appendLine("# Generated by Clikt")
            appendLine()
            generatePowershellForCommand(command, rootName, emptyList())
        }
    }

    private fun StringBuilder.generatePowershellForCommand(
        command: BaseCliktCommand<*>,
        rootName: String,
        parentNames: List<String>,
    ) {
        val commandName = command.commandName
        val depth = parentNames.size + 1
        val commandPath = parentNames + commandName
        val options = command._options.filterNot { it.hidden }
        val arguments = command._arguments
        val subcommands = command._subcommands
        val hasSubcommands = subcommands.isNotEmpty()
        val optionsWithValues = options.filter { it.nvalues.first > 0 }

        appendLine("# Register-ArgumentCompleter: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter")
        appendLine("Register-ArgumentCompleter -Native -CommandName '$rootName' -ScriptBlock {")
        appendLine("    param(\$wordToComplete, \$commandAst, \$cursorPosition)")
        appendLine()

        appendLine("# Build command-path from BareWord AST nodes to determine subcommand context depth")
        appendLine("# See about_Functions_Argument_Completion:")
        appendLine("# https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_argument_completion")
        appendLine("    \$commandPath = @()")
        appendLine("    for (\$i = 1; \$i -lt \$commandAst.CommandElements.Count; \$i++) {")
        appendLine("        \$e = \$commandAst.CommandElements[\$i]")
        appendLine("        if (\$e -is [StringConstantExpressionAst] -and \$e.StringConstantType -eq [StringConstantType]::BareWord -and -not \$e.Value.StartsWith('-')) {")
        appendLine("            \$commandPath += \$e.Value")
        appendLine("        }")
        appendLine("    }")
        appendLine()

        appendLine("# Guard: return early if the current context depth does not match this command level")
        if (parentNames.isEmpty()) {
            appendLine("    if (\$commandPath.Count -gt 0) { return }")
        } else {
            appendLine("    if (\$commandPath.Count -lt $depth) { return }")
            append("    if (")
            for ((j, parent) in parentNames.withIndex()) {
                if (j > 0) append(" -or ")
                append("\$commandPath[$j] -ne '${parent.escSingleQuote}'")
            }
            appendLine(") { return }")
        }
        appendLine()

        val optionNames = options.flatMap { it.allNames }.filter { it.startsWith('-') }
        if (optionNames.isNotEmpty()) {
            appendLine("# Complete option names (when word starts with `-`)")
            appendLine("    if (\$wordToComplete -match '^-') {")
            appendLine("        return @(")
            for (option in options) {
                for (name in option.allNames.filter { it.startsWith('-') }) {
                    val help = option.optionHelp(command.currentContext)
                        .takeWhile { it !in "\r\n" }
                        .escSingleQuote
                    appendLine("            [CompletionResult]::new('$name', '$name', [CompletionResultType]::ParameterName, '$help')")
                }
            }
            appendLine("        ) | Where-Object { \$_.CompletionText -like \"\$wordToComplete*\" }")
            appendLine("    }")
            appendLine()
        }

        if (optionsWithValues.isNotEmpty()) {
            appendLine("# Complete option values: check last element (cursor at option name), then second-to-last (cursor at value)")
            appendLine("    \$lastElement = \$commandAst.CommandElements[\$commandAst.CommandElements.Count - 1]")
            appendLine("    \$lastText = \$lastElement.Value")
            appendLine()
            appendLine("    if (\$lastText.StartsWith('-')) {")
            appendLine("        switch -Regex (\$lastText) {")
            for (option in optionsWithValues) {
                val names = option.allNames.filter { it.startsWith('-') }
                if (names.isEmpty()) continue
                val pattern = names.joinToString("|") { it.escRegex }
                appendLine("            '^($pattern)$' {")
                appendParamCompletion(option.completionCandidates, "                ")
                appendLine("                return")
                appendLine("            }")
            }
            appendLine("        }")
            appendLine("    } elseif (\$commandAst.CommandElements.Count -gt 2) {")
            appendLine("        \$prevElement = \$commandAst.CommandElements[\$commandAst.CommandElements.Count - 2]")
            appendLine("        \$prevText = \$prevElement.Value")
            appendLine("        if (\$prevText.StartsWith('-')) {")
            appendLine("            switch -Regex (\$prevText) {")
            for (option in optionsWithValues) {
                val names = option.allNames.filter { it.startsWith('-') }
                if (names.isEmpty()) continue
                val pattern = names.joinToString("|") { it.escRegex }
                appendLine("                '^($pattern)$' {")
                appendParamCompletion(option.completionCandidates, "                    ")
                appendLine("                    return")
                appendLine("                }")
            }
            appendLine("            }")
            appendLine("        }")
            appendLine("    }")
            appendLine()
        }

        appendLine("# Fallback: complete subcommand names or argument values")
        val hasAnyCompletions = hasSubcommands || arguments.isNotEmpty()
        if (hasAnyCompletions) {
            appendLine("    return @(")
            if (hasSubcommands) {
                for (sub in subcommands) {
                    val help = sub.help(sub.currentContext).escSingleQuote
                    appendLine("        [CompletionResult]::new('${sub.commandName}', '${sub.commandName}', [CompletionResultType]::ParameterValue, '$help')")
                }
            }
            for (argument in arguments) {
                val help = argument.getArgumentHelp(command.currentContext).escSingleQuote
                val cc = argument.completionCandidates
                when (cc) {
                    is CompletionCandidates.None -> {
                        appendLine("        [CompletionResult]::new('${argument.name}', '${argument.name}', [CompletionResultType]::ParameterValue, '$help')")
                    }
                    is CompletionCandidates.Path -> {
                        appendLine("        Get-ChildItem \"\$wordToComplete*\" -ErrorAction SilentlyContinue | ForEach-Object { [CompletionResult]::new(\$_.FullName, \$_.FullName, [CompletionResultType]::ParameterValue, '') }")
                    }
                    is CompletionCandidates.Hostname -> {
                    }
                    is CompletionCandidates.Username -> {
                        appendLine("        Get-LocalUser -ErrorAction SilentlyContinue | Where-Object { \$_.Name -like \"\$wordToComplete*\" } | ForEach-Object { [CompletionResult]::new(\$_.Name, \$_.Name, [CompletionResultType]::ParameterValue, '') }")
                    }
                    is CompletionCandidates.Fixed -> {
                        for (candidate in cc.candidates) {
                            appendLine("        [CompletionResult]::new('${candidate.escSingleQuote}', '${candidate.escSingleQuote}', [CompletionResultType]::ParameterValue, '$help')")
                        }
                    }
                    is CompletionCandidates.Custom -> {
                        val custom = cc.generator(ShellType.POWERSHELL)
                        if (custom != null) {
                            appendLine("        $custom | ForEach-Object { [CompletionResult]::new(\$_, \$_, [CompletionResultType]::ParameterValue, '') }")
                        }
                    }
                }
            }
            appendLine("    ) | Where-Object { \$_.CompletionText -like \"\$wordToComplete*\" }")
        }

        append("}")

        for (subcommand in subcommands) {
            appendLine()
            appendLine()
            generatePowershellForCommand(subcommand, rootName, commandPath)
        }
    }

    private fun StringBuilder.appendParamCompletion(cc: CompletionCandidates, indent: String) {
        val i2 = indent + "    "
        when (cc) {
            is CompletionCandidates.None -> {}
            is CompletionCandidates.Path -> {
                appendLine("${indent}Get-ChildItem \"\$wordToComplete*\" -ErrorAction SilentlyContinue | ForEach-Object { [CompletionResult]::new(\$_.FullName, \$_.FullName, [CompletionResultType]::ParameterValue, '') }")
            }
            is CompletionCandidates.Hostname -> {}
            is CompletionCandidates.Username -> {
                appendLine("${indent}Get-LocalUser -ErrorAction SilentlyContinue | Where-Object { \$_.Name -like \"\$wordToComplete*\" } | ForEach-Object { [CompletionResult]::new(\$_.Name, \$_.Name, [CompletionResultType]::ParameterValue, '') }")
            }
            is CompletionCandidates.Fixed -> {
                appendLine("${indent}return @(")
                for (candidate in cc.candidates) {
                    appendLine("${i2}[CompletionResult]::new('${candidate.escSingleQuote}', '${candidate.escSingleQuote}', [CompletionResultType]::ParameterValue, '')")
                }
                appendLine("${indent}) | Where-Object { \$_.CompletionText -like \"\$wordToComplete*\" }")
            }
            is CompletionCandidates.Custom -> {
                val custom = cc.generator(ShellType.POWERSHELL)
                if (custom != null) {
                    appendLine("${indent}$custom | ForEach-Object { [CompletionResult]::new(\$_, \$_, [CompletionResultType]::ParameterValue, '') }")
                }
            }
        }
    }

    private val BaseCliktCommand<*>.hasPowershellCompletionRequirements: Boolean
        get() = _arguments.isNotEmpty()
                || _subcommands.isNotEmpty()
                || _options.flatMap { it.allNames }.any { it.startsWith('-') }

    private val Option.allNames get() = names + secondaryNames

    private val String.escSingleQuote: String
        get() = replace("'", "''")

    private val String.escRegex: String
        get() = replace(Regex("[.\\\\+*?\\[\\^\\]\$(){}|]")) { "\\${it.value}" }
}
