package com.github.ajalt.clikt.completion

@Suppress("unused")
class PowershellCompletionTest : CompletionTestBase("powershell") {
    override fun `explicit completion candidates expected`(): String {
        return """
        |# Command completion for c
        |# Generated by Clikt
        |
        |# Register-ArgumentCompleter: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter
        |Register-ArgumentCompleter -Native -CommandName 'c' -ScriptBlock {
        |    param(${'$'}wordToComplete, ${'$'}commandAst, ${'$'}cursorPosition)
        |
        |# Build command-path from BareWord AST nodes to determine subcommand context depth
        |# See about_Functions_Argument_Completion:
        |# https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_argument_completion
        |    ${'$'}commandPath = @()
        |    for (${'$'}i = 1; ${'$'}i -lt ${'$'}commandAst.CommandElements.Count; ${'$'}i++) {
        |        ${'$'}e = ${'$'}commandAst.CommandElements[${'$'}i]
        |        if (${'$'}e -is [StringConstantExpressionAst] -and ${'$'}e.StringConstantType -eq [StringConstantType]::BareWord -and -not ${'$'}e.Value.StartsWith('-')) {
        |            ${'$'}commandPath += ${'$'}e.Value
        |        }
        |    }
        |
        |# Guard: return early if the current context depth does not match this command level
        |    if (${'$'}commandPath.Count -gt 0) { return }
        |
        |# Complete option names (when word starts with `-`)
        |    if (${'$'}wordToComplete -match '^-') {
        |        return @(
        |            [CompletionResult]::new('--none', '--none', [CompletionResultType]::ParameterName, '')
        |            [CompletionResult]::new('--path', '--path', [CompletionResultType]::ParameterName, '')
        |            [CompletionResult]::new('--host', '--host', [CompletionResultType]::ParameterName, '')
        |            [CompletionResult]::new('--user', '--user', [CompletionResultType]::ParameterName, '')
        |            [CompletionResult]::new('--fixed', '--fixed', [CompletionResultType]::ParameterName, '')
        |        ) | Where-Object { ${'$'}_.CompletionText -like "${'$'}wordToComplete*" }
        |    }
        |
        |# Complete option values: check last element (cursor at option name), then second-to-last (cursor at value)
        |    ${'$'}lastElement = ${'$'}commandAst.CommandElements[${'$'}commandAst.CommandElements.Count - 1]
        |    ${'$'}lastText = ${'$'}lastElement.Value
        |
        |    if (${'$'}lastText.StartsWith('-')) {
        |        switch -Regex (${'$'}lastText) {
        |            '^(--none)${'$'}' {
        |                return
        |            }
        |            '^(--path)${'$'}' {
        |                Get-ChildItem "${'$'}wordToComplete*" -ErrorAction SilentlyContinue | ForEach-Object { [CompletionResult]::new(${'$'}_.FullName, ${'$'}_.FullName, [CompletionResultType]::ParameterValue, '') }
        |                return
        |            }
        |            '^(--host)${'$'}' {
        |                return
        |            }
        |            '^(--user)${'$'}' {
        |                Get-LocalUser -ErrorAction SilentlyContinue | Where-Object { ${'$'}_.Name -like "${'$'}wordToComplete*" } | ForEach-Object { [CompletionResult]::new(${'$'}_.Name, ${'$'}_.Name, [CompletionResultType]::ParameterValue, '') }
        |                return
        |            }
        |            '^(--fixed)${'$'}' {
        |                return @(
        |                    [CompletionResult]::new('foo', 'foo', [CompletionResultType]::ParameterValue, '')
        |                    [CompletionResult]::new('bar', 'bar', [CompletionResultType]::ParameterValue, '')
        |                ) | Where-Object { ${'$'}_.CompletionText -like "${'$'}wordToComplete*" }
        |                return
        |            }
        |        }
        |    } elseif (${'$'}commandAst.CommandElements.Count -gt 2) {
        |        ${'$'}prevElement = ${'$'}commandAst.CommandElements[${'$'}commandAst.CommandElements.Count - 2]
        |        ${'$'}prevText = ${'$'}prevElement.Value
        |        if (${'$'}prevText.StartsWith('-')) {
        |            switch -Regex (${'$'}prevText) {
        |                '^(--none)${'$'}' {
        |                    return
        |                }
        |                '^(--path)${'$'}' {
        |                    Get-ChildItem "${'$'}wordToComplete*" -ErrorAction SilentlyContinue | ForEach-Object { [CompletionResult]::new(${'$'}_.FullName, ${'$'}_.FullName, [CompletionResultType]::ParameterValue, '') }
        |                    return
        |                }
        |                '^(--host)${'$'}' {
        |                    return
        |                }
        |                '^(--user)${'$'}' {
        |                    Get-LocalUser -ErrorAction SilentlyContinue | Where-Object { ${'$'}_.Name -like "${'$'}wordToComplete*" } | ForEach-Object { [CompletionResult]::new(${'$'}_.Name, ${'$'}_.Name, [CompletionResultType]::ParameterValue, '') }
        |                    return
        |                }
        |                '^(--fixed)${'$'}' {
        |                    return @(
        |                        [CompletionResult]::new('foo', 'foo', [CompletionResultType]::ParameterValue, '')
        |                        [CompletionResult]::new('bar', 'bar', [CompletionResultType]::ParameterValue, '')
        |                    ) | Where-Object { ${'$'}_.CompletionText -like "${'$'}wordToComplete*" }
        |                    return
        |                }
        |            }
        |        }
        |    }
        |
        |# Fallback: complete subcommand names or argument values
        |    return @(
        |        Get-LocalUser -ErrorAction SilentlyContinue | Where-Object { ${'$'}_.Name -like "${'$'}wordToComplete*" } | ForEach-Object { [CompletionResult]::new(${'$'}_.Name, ${'$'}_.Name, [CompletionResultType]::ParameterValue, '') }
        |        [CompletionResult]::new('baz', 'baz', [CompletionResultType]::ParameterValue, '')
        |        [CompletionResult]::new('qux', 'qux', [CompletionResultType]::ParameterValue, '')
        |    ) | Where-Object { ${'$'}_.CompletionText -like "${'$'}wordToComplete*" }
        |}
        """
    }

    override fun `custom completions expected`(): String {
        return """
        |# Command completion for c
        |# Generated by Clikt
        |
        |# Register-ArgumentCompleter: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter
        |Register-ArgumentCompleter -Native -CommandName 'c' -ScriptBlock {
        |    param(${'$'}wordToComplete, ${'$'}commandAst, ${'$'}cursorPosition)
        |
        |# Build command-path from BareWord AST nodes to determine subcommand context depth
        |# See about_Functions_Argument_Completion:
        |# https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_argument_completion
        |    ${'$'}commandPath = @()
        |    for (${'$'}i = 1; ${'$'}i -lt ${'$'}commandAst.CommandElements.Count; ${'$'}i++) {
        |        ${'$'}e = ${'$'}commandAst.CommandElements[${'$'}i]
        |        if (${'$'}e -is [StringConstantExpressionAst] -and ${'$'}e.StringConstantType -eq [StringConstantType]::BareWord -and -not ${'$'}e.Value.StartsWith('-')) {
        |            ${'$'}commandPath += ${'$'}e.Value
        |        }
        |    }
        |
        |# Guard: return early if the current context depth does not match this command level
        |    if (${'$'}commandPath.Count -gt 0) { return }
        |
        |# Complete option names (when word starts with `-`)
        |    if (${'$'}wordToComplete -match '^-') {
        |        return @(
        |            [CompletionResult]::new('--o', '--o', [CompletionResultType]::ParameterName, '')
        |            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Show this message and exit')
        |            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Show this message and exit')
        |        ) | Where-Object { ${'$'}_.CompletionText -like "${'$'}wordToComplete*" }
        |    }
        |
        |# Complete option values: check last element (cursor at option name), then second-to-last (cursor at value)
        |    ${'$'}lastElement = ${'$'}commandAst.CommandElements[${'$'}commandAst.CommandElements.Count - 1]
        |    ${'$'}lastText = ${'$'}lastElement.Value
        |
        |    if (${'$'}lastText.StartsWith('-')) {
        |        switch -Regex (${'$'}lastText) {
        |            '^(--o)${'$'}' {
        |                & echo foo bar | ForEach-Object { ${'$'}_ } | ForEach-Object { [CompletionResult]::new(${'$'}_, ${'$'}_, [CompletionResultType]::ParameterValue, '') }
        |                return
        |            }
        |        }
        |    } elseif (${'$'}commandAst.CommandElements.Count -gt 2) {
        |        ${'$'}prevElement = ${'$'}commandAst.CommandElements[${'$'}commandAst.CommandElements.Count - 2]
        |        ${'$'}prevText = ${'$'}prevElement.Value
        |        if (${'$'}prevText.StartsWith('-')) {
        |            switch -Regex (${'$'}prevText) {
        |                '^(--o)${'$'}' {
        |                    & echo foo bar | ForEach-Object { ${'$'}_ } | ForEach-Object { [CompletionResult]::new(${'$'}_, ${'$'}_, [CompletionResultType]::ParameterValue, '') }
        |                    return
        |                }
        |            }
        |        }
        |    }
        |
        |# Fallback: complete subcommand names or argument values
        |    return @(
        |        (echo zzz xxx) | ForEach-Object { [CompletionResult]::new(${'$'}_, ${'$'}_, [CompletionResultType]::ParameterValue, '') }
        |    ) | Where-Object { ${'$'}_.CompletionText -like "${'$'}wordToComplete*" }
        |}
        """
    }

    override fun `arg names with spaces expected`(): String {
        return """
        |# Command completion for c
        |# Generated by Clikt
        |
        |# Register-ArgumentCompleter: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter
        |Register-ArgumentCompleter -Native -CommandName 'c' -ScriptBlock {
        |    param(${'$'}wordToComplete, ${'$'}commandAst, ${'$'}cursorPosition)
        |
        |# Build command-path from BareWord AST nodes to determine subcommand context depth
        |# See about_Functions_Argument_Completion:
        |# https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_argument_completion
        |    ${'$'}commandPath = @()
        |    for (${'$'}i = 1; ${'$'}i -lt ${'$'}commandAst.CommandElements.Count; ${'$'}i++) {
        |        ${'$'}e = ${'$'}commandAst.CommandElements[${'$'}i]
        |        if (${'$'}e -is [StringConstantExpressionAst] -and ${'$'}e.StringConstantType -eq [StringConstantType]::BareWord -and -not ${'$'}e.Value.StartsWith('-')) {
        |            ${'$'}commandPath += ${'$'}e.Value
        |        }
        |    }
        |
        |# Guard: return early if the current context depth does not match this command level
        |    if (${'$'}commandPath.Count -gt 0) { return }
        |
        |# Complete option names (when word starts with `-`)
        |    if (${'$'}wordToComplete -match '^-') {
        |        return @(
        |            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Show this message and exit')
        |            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Show this message and exit')
        |        ) | Where-Object { ${'$'}_.CompletionText -like "${'$'}wordToComplete*" }
        |    }
        |
        |# Fallback: complete subcommand names or argument values
        |    return @(
        |        [CompletionResult]::new('foo bar', 'foo bar', [CompletionResultType]::ParameterValue, 'help')
        |    ) | Where-Object { ${'$'}_.CompletionText -like "${'$'}wordToComplete*" }
        |}
        """
    }

    override fun `option secondary names expected`(): String {
        return """
        |# Command completion for c
        |# Generated by Clikt
        |
        |# Register-ArgumentCompleter: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter
        |Register-ArgumentCompleter -Native -CommandName 'c' -ScriptBlock {
        |    param(${'$'}wordToComplete, ${'$'}commandAst, ${'$'}cursorPosition)
        |
        |# Build command-path from BareWord AST nodes to determine subcommand context depth
        |# See about_Functions_Argument_Completion:
        |# https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_argument_completion
        |    ${'$'}commandPath = @()
        |    for (${'$'}i = 1; ${'$'}i -lt ${'$'}commandAst.CommandElements.Count; ${'$'}i++) {
        |        ${'$'}e = ${'$'}commandAst.CommandElements[${'$'}i]
        |        if (${'$'}e -is [StringConstantExpressionAst] -and ${'$'}e.StringConstantType -eq [StringConstantType]::BareWord -and -not ${'$'}e.Value.StartsWith('-')) {
        |            ${'$'}commandPath += ${'$'}e.Value
        |        }
        |    }
        |
        |# Guard: return early if the current context depth does not match this command level
        |    if (${'$'}commandPath.Count -gt 0) { return }
        |
        |# Complete option names (when word starts with `-`)
        |    if (${'$'}wordToComplete -match '^-') {
        |        return @(
        |            [CompletionResult]::new('--flag', '--flag', [CompletionResultType]::ParameterName, '')
        |            [CompletionResult]::new('--no-flag', '--no-flag', [CompletionResultType]::ParameterName, '')
        |            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Show this message and exit')
        |            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Show this message and exit')
        |        ) | Where-Object { ${'$'}_.CompletionText -like "${'$'}wordToComplete*" }
        |    }
        |
        |# Fallback: complete subcommand names or argument values
        |}
        """
    }

    override fun `subcommands with multi-word names expected`(): String {
        return """
        |# Command completion for c
        |# Generated by Clikt
        |
        |# Register-ArgumentCompleter: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter
        |Register-ArgumentCompleter -Native -CommandName 'c' -ScriptBlock {
        |    param(${'$'}wordToComplete, ${'$'}commandAst, ${'$'}cursorPosition)
        |
        |# Build command-path from BareWord AST nodes to determine subcommand context depth
        |# See about_Functions_Argument_Completion:
        |# https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_argument_completion
        |    ${'$'}commandPath = @()
        |    for (${'$'}i = 1; ${'$'}i -lt ${'$'}commandAst.CommandElements.Count; ${'$'}i++) {
        |        ${'$'}e = ${'$'}commandAst.CommandElements[${'$'}i]
        |        if (${'$'}e -is [StringConstantExpressionAst] -and ${'$'}e.StringConstantType -eq [StringConstantType]::BareWord -and -not ${'$'}e.Value.StartsWith('-')) {
        |            ${'$'}commandPath += ${'$'}e.Value
        |        }
        |    }
        |
        |# Guard: return early if the current context depth does not match this command level
        |    if (${'$'}commandPath.Count -gt 0) { return }
        |
        |# Complete option names (when word starts with `-`)
        |    if (${'$'}wordToComplete -match '^-') {
        |        return @(
        |            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Show this message and exit')
        |            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Show this message and exit')
        |        ) | Where-Object { ${'$'}_.CompletionText -like "${'$'}wordToComplete*" }
        |    }
        |
        |# Fallback: complete subcommand names or argument values
        |    return @(
        |        [CompletionResult]::new('sub', 'sub', [CompletionResultType]::ParameterValue, '')
        |        [CompletionResult]::new('sub-command', 'sub-command', [CompletionResultType]::ParameterValue, '')
        |    ) | Where-Object { ${'$'}_.CompletionText -like "${'$'}wordToComplete*" }
        |}
        |
        |# Register-ArgumentCompleter: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter
        |Register-ArgumentCompleter -Native -CommandName 'c' -ScriptBlock {
        |    param(${'$'}wordToComplete, ${'$'}commandAst, ${'$'}cursorPosition)
        |
        |# Build command-path from BareWord AST nodes to determine subcommand context depth
        |# See about_Functions_Argument_Completion:
        |# https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_argument_completion
        |    ${'$'}commandPath = @()
        |    for (${'$'}i = 1; ${'$'}i -lt ${'$'}commandAst.CommandElements.Count; ${'$'}i++) {
        |        ${'$'}e = ${'$'}commandAst.CommandElements[${'$'}i]
        |        if (${'$'}e -is [StringConstantExpressionAst] -and ${'$'}e.StringConstantType -eq [StringConstantType]::BareWord -and -not ${'$'}e.Value.StartsWith('-')) {
        |            ${'$'}commandPath += ${'$'}e.Value
        |        }
        |    }
        |
        |# Guard: return early if the current context depth does not match this command level
        |    if (${'$'}commandPath.Count -lt 2) { return }
        |    if (${'$'}commandPath[0] -ne 'c') { return }
        |
        |# Complete option names (when word starts with `-`)
        |    if (${'$'}wordToComplete -match '^-') {
        |        return @(
        |            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Show this message and exit')
        |            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Show this message and exit')
        |        ) | Where-Object { ${'$'}_.CompletionText -like "${'$'}wordToComplete*" }
        |    }
        |
        |# Fallback: complete subcommand names or argument values
        |}
        |
        |# Register-ArgumentCompleter: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter
        |Register-ArgumentCompleter -Native -CommandName 'c' -ScriptBlock {
        |    param(${'$'}wordToComplete, ${'$'}commandAst, ${'$'}cursorPosition)
        |
        |# Build command-path from BareWord AST nodes to determine subcommand context depth
        |# See about_Functions_Argument_Completion:
        |# https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_argument_completion
        |    ${'$'}commandPath = @()
        |    for (${'$'}i = 1; ${'$'}i -lt ${'$'}commandAst.CommandElements.Count; ${'$'}i++) {
        |        ${'$'}e = ${'$'}commandAst.CommandElements[${'$'}i]
        |        if (${'$'}e -is [StringConstantExpressionAst] -and ${'$'}e.StringConstantType -eq [StringConstantType]::BareWord -and -not ${'$'}e.Value.StartsWith('-')) {
        |            ${'$'}commandPath += ${'$'}e.Value
        |        }
        |    }
        |
        |# Guard: return early if the current context depth does not match this command level
        |    if (${'$'}commandPath.Count -lt 2) { return }
        |    if (${'$'}commandPath[0] -ne 'c') { return }
        |
        |# Complete option names (when word starts with `-`)
        |    if (${'$'}wordToComplete -match '^-') {
        |        return @(
        |            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Show this message and exit')
        |            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Show this message and exit')
        |        ) | Where-Object { ${'$'}_.CompletionText -like "${'$'}wordToComplete*" }
        |    }
        |
        |# Fallback: complete subcommand names or argument values
        |    return @(
        |        [CompletionResult]::new('sub-sub', 'sub-sub', [CompletionResultType]::ParameterValue, '')
        |        [CompletionResult]::new('long-sub-command', 'long-sub-command', [CompletionResultType]::ParameterValue, '')
        |    ) | Where-Object { ${'$'}_.CompletionText -like "${'$'}wordToComplete*" }
        |}
        |
        |# Register-ArgumentCompleter: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter
        |Register-ArgumentCompleter -Native -CommandName 'c' -ScriptBlock {
        |    param(${'$'}wordToComplete, ${'$'}commandAst, ${'$'}cursorPosition)
        |
        |# Build command-path from BareWord AST nodes to determine subcommand context depth
        |# See about_Functions_Argument_Completion:
        |# https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_argument_completion
        |    ${'$'}commandPath = @()
        |    for (${'$'}i = 1; ${'$'}i -lt ${'$'}commandAst.CommandElements.Count; ${'$'}i++) {
        |        ${'$'}e = ${'$'}commandAst.CommandElements[${'$'}i]
        |        if (${'$'}e -is [StringConstantExpressionAst] -and ${'$'}e.StringConstantType -eq [StringConstantType]::BareWord -and -not ${'$'}e.Value.StartsWith('-')) {
        |            ${'$'}commandPath += ${'$'}e.Value
        |        }
        |    }
        |
        |# Guard: return early if the current context depth does not match this command level
        |    if (${'$'}commandPath.Count -lt 3) { return }
        |    if (${'$'}commandPath[0] -ne 'c' -or ${'$'}commandPath[1] -ne 'sub-command') { return }
        |
        |# Complete option names (when word starts with `-`)
        |    if (${'$'}wordToComplete -match '^-') {
        |        return @(
        |            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Show this message and exit')
        |            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Show this message and exit')
        |        ) | Where-Object { ${'$'}_.CompletionText -like "${'$'}wordToComplete*" }
        |    }
        |
        |# Fallback: complete subcommand names or argument values
        |}
        |
        |# Register-ArgumentCompleter: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter
        |Register-ArgumentCompleter -Native -CommandName 'c' -ScriptBlock {
        |    param(${'$'}wordToComplete, ${'$'}commandAst, ${'$'}cursorPosition)
        |
        |# Build command-path from BareWord AST nodes to determine subcommand context depth
        |# See about_Functions_Argument_Completion:
        |# https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_argument_completion
        |    ${'$'}commandPath = @()
        |    for (${'$'}i = 1; ${'$'}i -lt ${'$'}commandAst.CommandElements.Count; ${'$'}i++) {
        |        ${'$'}e = ${'$'}commandAst.CommandElements[${'$'}i]
        |        if (${'$'}e -is [StringConstantExpressionAst] -and ${'$'}e.StringConstantType -eq [StringConstantType]::BareWord -and -not ${'$'}e.Value.StartsWith('-')) {
        |            ${'$'}commandPath += ${'$'}e.Value
        |        }
        |    }
        |
        |# Guard: return early if the current context depth does not match this command level
        |    if (${'$'}commandPath.Count -lt 3) { return }
        |    if (${'$'}commandPath[0] -ne 'c' -or ${'$'}commandPath[1] -ne 'sub-command') { return }
        |
        |# Complete option names (when word starts with `-`)
        |    if (${'$'}wordToComplete -match '^-') {
        |        return @(
        |            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Show this message and exit')
        |            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Show this message and exit')
        |        ) | Where-Object { ${'$'}_.CompletionText -like "${'$'}wordToComplete*" }
        |    }
        |
        |# Fallback: complete subcommand names or argument values
        |}
        """
    }

}
